parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dovecot-logs
- crowdsecurity/postscreen-logs
- crowdsecurity/postfix-logs
- parsers/s01-parse/aritas1/dockermailserver-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: docker-mailserver.log
log_type: syslog
labels: {}
ignore_parsers: false
